### PR TITLE
pyDKB stage fix (pt.14)

### PR DESCRIPTION
**Pull request by mgolosova**
Test and fixing of `-i input_dir` without file names (it is supposed to use all files with specific extension).

---
+ (pt.13) #215

### CODE REVIEW

**Comment by mgolosova** [comment]
During rebase I saw test case 27 unexpectedly failed; somehow this time files went to processing in a different order. So I added 68d2633, which prevents such an unstable behaviour.

**Comment by anastasiakaida** [comment]
@mgolosova 

In case 27, I got an output which is a little bit different than it should be.

```
.../Utils/Dataflow/test/pyDKB $ ./json2TTL.py -d s -i ./input
(INFO) (ProcessorStage) Configuration parameters:
(INFO) (ProcessorStage)   hdfs        : 'False'
(INFO) (ProcessorStage)   dest        : 's'
(INFO) (ProcessorStage)   input_dir   : './input'
(INFO) (ProcessorStage)   eom         : '\n'
(INFO) (ProcessorStage)   output_dir  : 'out'
(INFO) (ProcessorStage)   source      : 'f'
(INFO) (ProcessorStage)   eop         : ''
(INFO) (ProcessorStage)   mode        : 'f'
(INFO) (ProcessorStage)   config      : 'None'
(INFO) (ProcessorStage)   input_files : '[]'
(INFO) (ProcessorStage) Starting stage execution.
(WARN) (InputStream) Failed to read input message as JSON.
(==) Cause: Extra data: line 1 column 10 - line 1 column 22 (char 9 - 21)
(==) Original message: '{"A":"B"}EOM{"C":"D",'
(WARN) (InputStream) Unexpected end of stream, skipping rest of input:
(==) '"E":"F"}EOM'
(WARN) (InputStream) Failed to read input message as JSON.
(==) Cause: Extra data: line 1 column 10 - line 1 column 22 (char 9 - 21)
(==) Original message: '{"A":"B"}EOM{"C":"D",'
(WARN) (InputStream) Failed to read input message as JSON.
(==) Cause: Extra data: line 1 column 4 - line 1 column 37 (char 3 - 36)
(==) Original message: '"E":"F"}EOM"Unfinished message......'
{u'a': u'value_1'}
{u'c': u'val_3', u'b': u'val_2'}
{u'd': None}
{u'a': 11}
{u'c': 33, u'b': 22}
{u'd': 44}
{u'a': 11}
{u'c': 33, u'b': 22}
{u'd': 44}
(WARN) (InputStream) Unexpected end of stream, skipping rest of input:
(==) 'Unfinished<...>ge is here'
(WARN) (InputStream) Failed to read input message as JSON.
(==) Cause: Expecting object: line 1 column 1 (char 0)
(==) Original message: '['
(WARN) (InputStream) Failed to read input message as JSON.
(==) Cause: Extra data: line 1 column 10 - line 1 column 21 (char 9 - 20)
(==) Original message: '{"a": 11}, {"b": 22,'
(WARN) (InputStream) Failed to read input message as JSON.
(==) Cause: Extra data: line 1 column 4 - line 1 column 10 (char 3 - 9)
(==) Original message: '"c": 33},'
{u'd': 44}
(WARN) (InputStream) Failed to read input message as JSON.
(==) Cause: No JSON object could be decoded
(==) Original message: ']'
(INFO) (ProcessorStage) Stopping stage.
```

Is it supposed to be or not?

**Comment by mgolosova** [comment]
@anastasiakaida, do you mean output (stdout) or error stream (stderr) or both of them?
Output looks fine for me, will try to check the error...
Would be helpful if you could attach `err.tmp` and `out.tmp`, temporary files that created when you run `./test.sh -c 27` (they will appear in `Utils/Dataflow/test/pyDKB` directory).

**Comment by anastasiakaida** [comment]
@mgolosova 
I checked what I received in err.tmp -- it looks fine ass well as out.tmp, so this commit is also approved.

err.tmp content:
```
(INFO) (ProcessorStage) Configuration parameters:
(INFO) (ProcessorStage)   hdfs        : 'False'
(INFO) (ProcessorStage)   dest        : 's'
(INFO) (ProcessorStage)   input_dir   : './input'
(INFO) (ProcessorStage)   eom         : '\n'
(INFO) (ProcessorStage)   output_dir  : 'out'
(INFO) (ProcessorStage)   source      : 'f'
(INFO) (ProcessorStage)   eop         : ''
(INFO) (ProcessorStage)   mode        : 'f'
(INFO) (ProcessorStage)   config      : 'None'
(INFO) (ProcessorStage)   input_files : '[]'
(INFO) (ProcessorStage) Starting stage execution.
(WARN) (InputStream) Failed to read input message as JSON.
(==) Cause: Extra data: line 1 column 10 - line 1 column 22 (char 9 - 21)
(==) Original message: '{"A":"B"}EOM{"C":"D",'
(WARN) (InputStream) Unexpected end of stream, skipping rest of input:
(==) '"E":"F"}EOM'
(WARN) (InputStream) Failed to read input message as JSON.
(==) Cause: Extra data: line 1 column 10 - line 1 column 22 (char 9 - 21)
(==) Original message: '{"A":"B"}EOM{"C":"D",'
(WARN) (InputStream) Failed to read input message as JSON.
(==) Cause: Extra data: line 1 column 4 - line 1 column 37 (char 3 - 36)
(==) Original message: '"E":"F"}EOM"Unfinished message......'
(WARN) (InputStream) Unexpected end of stream, skipping rest of input:
(==) 'Unfinished<...>ge is here'
(WARN) (InputStream) Failed to read input message as JSON.
(==) Cause: Expecting object: line 1 column 1 (char 0)
(==) Original message: '['
(WARN) (InputStream) Failed to read input message as JSON.
(==) Cause: Extra data: line 1 column 10 - line 1 column 21 (char 9 - 20)
(==) Original message: '{"a": 11}, {"b": 22,'
(WARN) (InputStream) Failed to read input message as JSON.
(==) Cause: Extra data: line 1 column 4 - line 1 column 10 (char 3 - 9)
(==) Original message: '"c": 33},'
(WARN) (InputStream) Failed to read input message as JSON.
(==) Cause: No JSON object could be decoded
(==) Original message: ']'
(INFO) (ProcessorStage) Stopping stage.
```

**Pull request merged**
