### PR TITLE
Merge 'master' into 'pyDKB'

### PR DESCRIPTION
**Pull request by mgolosova**
Two main reasons for this merge:
* there were some changes to pyDKB lib in `master` branch,
* CI (continuous integration) checks has changed.

To go on with pyDKB development, I think it is better to make this merge in advance.

Due to the merge conflict in `pyDKB/dataflow/stage/AbstractStage.py`, the merge is done in a separate PR (instead of a direct PR from `master` to `pyDKB`).

ToDo:
- [x] update DF stages (remove `try/except` around pyDKB `stage`, as it became excessive for now).

### CODE REVIEW

**Comment by mgolosova** [comment]
Changed PR status to `WIP`, as realized that it would be a good idea to update Dataflow stages according to the new paradigm of error handlinge (in particular, remove excessive `try/except` clauses).

**Comment by mgolosova** [comment]
`WIP` status solved.

**Comment by mgolosova** [comment]
Made one more merge from master to have in pyDKB the changes, related to the updated requirements from `pycodestyle` Travis check.

**Comment by anastasiakaida** [comment]
I've found a typo in [this](https://github.com/PanDAWMS/dkb/pull/119/commits/8b4c589270f61015db39b9901a5ded1c8da54fd5) commit. -- 'eny'

**Comment by mgolosova** [comment]
@anastasiakaida,
oh, shame on me :( thank you! Fixed now.

**Pull request merged**
