### PR TITLE
pyDKB stage fix (pt.7)

### PR DESCRIPTION
**Pull request by mgolosova**
EOM handling:
* test cases;
* library fixes.
---
+ (pt.6) #207

### CODE REVIEW

**Comment by mgolosova** [comment]
@anastasiakaida,

> There should be "reads" instead of "read" in the 54dfc97 description.

Do you mean "is/be fully read" parts? It\`s "to be + Past Participle", wich is "read" for "read" ;)

**Comment by anastasiakaida** [comment]
@mgolosova 
I apologize a lot! It's about 42cfb8f.

```
When stage read input with custom EOM, it read first message, and then
'resetted' input stream, loosing buffered in `custom_readline()` generator
data.
```
Maybe ```When stage reads <...>, it read first <...>```?

**Comment by mgolosova** [comment]
@anastasiakaida, no, I meant to say it in the past (which is also "read" ;) ). Will change to "used to read" to avoid confuses...

**Comment by anastasiakaida** [comment]
@mgolosova Ok, thank you!

**Comment by mgolosova** [comment]
@anastasiakaida, thank you for the reminder, rewording done.

**Pull request merged**
