### PR TITLE
Stage 030 update

### PR DESCRIPTION
**Pull request by Evildoor**
Small update with changes serving for:

- Catching up with dataflow-with-document-content -> master migration.
- ~~Creating a base for extension development.~~ (Removed per conversation below.)

### CODE REVIEW

**Comment by Evildoor** [comment]
CSV file - i added it because i thought that it was better than either:

1. Making a commit which does nothing besides creating a directory.
2. Not making a commit, and then creating this directory in each branch which adds an extension.

Error - makes sense, will try to keep that in mind.

Regular expression - this change is solving #46. When this pull request will be merged, issue will be closed and commit/request will be linked in it. I can link issue here or in pull request initial message, but not in commit message (i think).

**Comment by mgolosova** [comment]
@Evildoor,
I see the problem.
For Git itself, there\`s nothing wrong in same dir created in different branches -- as it is interested mostly in files, to create or delete a directory is kind of a "side-effect" of adding/removing data from it. Git would only worry if you add different files with the same name, and then try to merge them.

However if there are too many branches, and you\`d like to avoid `mkdir` for each of them, I would recomend to create a branch like "stage-30-extensions", create empty dir [1] (or put there all the source data you are gonna need for the extensions), and then create branches for individual extensions from that one.
Then even if you create PR from that branches directly to the `master` branch, the "create empty dir" commit will disappear from all the PRs as soon as the first one is merged.

[1] As Git is not interested in any directory unless it has at least one tracked file, to add an empty dir is a tricky thing. But you can add something like README file to it, where you are going to make notes about "which data are for which extension" (if it is a directory for source data only) or describing extensions themselves (if their code to be stored in it as well), or something.

**Comment by Evildoor** [comment]
I doubt that there will be too many branches with different extensions, but idea of creating stage-30-extensions branch looks appealing to me. Will do.

**Comment by Evildoor** [comment]
Removed commit related to extensions, updated descriptions for other ones.

**Comment by mgolosova** [comment]
@Evildoor,
Thank you, I think the PR can be merged now.
Just ine question: am I right and the 862e7cb is related to the issue #14? I`d like to mention it in the merge commit at least, as in console no one will see cross-links that will possibly appear later in the web-interface ;-)

**Comment by Evildoor** [comment]
@mgolosova 
Good.
Uh, no, 862e7cb is related to #46, not #14.

**Comment by mgolosova** [comment]
@Evildoor,
right, thank you. Was not that obvious ;)

**Comment by mgolosova** [comment]
@Evildoor ,
request merged, thank you. Please remove the branch if it is no longer needed.

**Pull request merged**
