### PR TITLE
Stage 030 pycodestyle

### PR DESCRIPTION
**Pull request by Evildoor**
Fixed two issues discovered by pycodestyle.

### CODE REVIEW

**Comment by mgolosova** [comment]
Thank you!
The request will be reviewed till the end of tomorrow.

**Comment by Evildoor** [comment]
Thanks for finding those cases, will check them later this week.

**Comment by anastasiakaida** [comment]
@Evildoor,

Unfortunately, I've found some errors with flake8. I think it would be great to fix it:
`manager.py:70:9: F401 'tkFileDialog.askopenfilename' imported but unused
`
In `manager.py` you use _askopenfilenames_ so it would be nice to exclude _askopenfilename_ if you are not going to use it next time.

`manager.py:1273:21: F841 local variable 'bt' is assigned to but never used`
For what purpose `bt` was created if it is unused?
___________
Also, I have some questions for better understanding how this module works. I'll write it tomorrow.

Thank you!

**Comment by Evildoor** [comment]
@anastasiakaida 

askopenfilename - at some point it was used, then all instances of it were removed or replaced with askopenfilenames.

bt - i don't remember exactly since this function (half-interactive title determination) was created long time ago and it's not used because we have better methods of obtaining paper title (outside of PDF Analyzer). By the looks of the code, it seems that it was used for shortening long possible titles, which is no longer necessary since Tkinter displays them just fine.

Thanks for bringing these problems to my attention, i will fix them.

Sure, i'm open to questions regarding this module. However, unless they are related to coding style discussed here, they should be asked elsewhere (via email, for example).

**Comment by mgolosova** [comment]
I am really sorry for the delay. Seems like it is totally OK and can be merged.

My question is: may I merge this PR into #96, so that all the related changes will get to master with one merge (maybe a bit later, but all at once)?

**Comment by Evildoor** [comment]
No worries, this is not urgent.

Sure, go ahead.

**Comment by mgolosova** [comment]
@Evildoor,
thank you. The request is merged.

Please remove the branch if it is no longer needed.

**Pull request merged**
