### PR TITLE
pyDKB/test: messages decode.

### PR DESCRIPTION
**Pull request by mgolosova**
Some issues that affect operations with JSON messages are related to not very accurate handling of the message content: we assume that it is a dict, while in theory it can be of any type that corresponds to a JSON objects. In test cases, at least, some of JSON messages contain lists, not hashes.

Currently those issues are visible when attemt to "decode" a message initialized with (supposedly) valid JSON object (list, number...). So new test cases are using furced decoding of output messages -- to make sure that the decoding process at leas not produces any errors.

Forced decoding is added to existing test stages as an optional parameter `--decode`, since I didn't want to change behaviour of all the existing test cases (while it might be a wrong decision: after all, additional message "decoding" must not affect the output value, produced by `content()` method...).

The only change in pyDKB:
* list of 'native' types for JSON message is extended with `list`, `int`, `float`.

Changes in tests:
* `--decode` option;
* more accurate creation of output messages from the content of input ones;
* more accurate check for presence of `"stop"` in the input data.

### CODE REVIEW

**Comment by Evildoor** [comment]
Three tests are failing when I'm trying to run `test.sh`.

    FAIL: 27 (STDOUT) (cmd: './json2TTL.py -d s -i ./input')
    ...
    FAIL: 39 (STDOUT) (cmd: 'cat input/NDjson-natives.json | ./json2JSON.py -m s --decode')
    FAIL: 39 (STDERR) (cmd: 'cat input/NDjson-natives.json | ./json2JSON.py -m s --decode')
    FAIL: 40 (STDOUT) (cmd: 'cat input/NDjson-natives.json | ./json2TTL.py -m s --decode')
    FAIL: 40 (STDERR) (cmd: 'cat input/NDjson-natives.json | ./json2TTL.py -m s --decode')

**Comment by mgolosova** [comment]
@Evildoor,
> Three tests are failing when I'm trying to run test.sh. Is this normal?

Of course it is not :) I didn't add the new sample file required for the new tests, and it also affected a test that uses *all* samples. Thank you for pointing out, fixed now.

---

BTW: failed tests generate debug files that might be helpful to see what's wrong:
```
/Utils/Dataflow/test/pyDKB$ cat 40_out.diff
--- case/40/out 2020-03-24 10:47:11.027443659 +0000
+++ out.tmp     2020-03-24 10:47:56.815755466 +0000
@@ -1,6 +0,0 @@
-{u'a': u'b'}
-[u'a', u'b']
-123
-aaaaaa
-15.5
-
\ No newline at end of file
/Utils/Dataflow/test/pyDKB$ cat 40_err.diff
--- case/40/err 2020-03-24 10:47:11.027443659 +0000
+++ err.tmp     2020-03-24 10:47:56.875755875 +0000
@@ -1,3 +1,4 @@
+cat: input/NDjson-natives.json: No such file or directory
 (INFO) (ProcessorStage) Configuration parameters:
 (INFO) (ProcessorStage)   hdfs         : 'False'
 (INFO) (ProcessorStage)   dest         : 's'
```

**Comment by mgolosova** [comment]
Have to close/reopen the PR to try and run Travis checks.
@Evildoor, should it work -- I'll ask you to re-approve the PR.

**Comment by mgolosova** [comment]
Looks like there's some problem with Travis/GitHub integration; will wait a little (till tomorrow?) and see if something changes; if not -- will look into it more carefully.

**Comment by mgolosova** [comment]
Will try again with re-opening this PR...

**Comment by mgolosova** [comment]
@Evildoor,

After your approval I made 2 forced pushes:
> @mgolosova [force-pushed](https://github.com/PanDAWMS/dkb/compare/06437e047cafb5a14e6dc5a6ab2f43db964302cc..71070a51890d396d7d1972f95f9c02e5396f6db9) the pyDKB-test-messages-decode branch from 06437e0 to 71070a5

> @mgolosova [force-pushed](https://github.com/PanDAWMS/dkb/compare/47af7f80e06c4c53f2cba9a5c9654cf926d1e57c..50e5cb525d826476677d91fa80109c92da502305) the pyDKB-test-messages-decode branch from 47af7f8 to 50e5cb5

...and merged here `master` branch.
Both forced pushes were about rewording the `pyDKB/test: add missed in previous commits data sample.` commit (at first attempt I specified the wrong commit in the log message).

Please take a look, and re-approve if everything's fine.

**Pull request merged**
