### PR TITLE
Stage 019: markers

### PR DESCRIPTION
**Pull request by mgolosova**
Suddenly realized that processing stage 019_esFormat does not follow the EOM/EOP marker paradigm.
For now it is OK, but when we switch to Kafka-supervised version of the dataflow, it will be embarassing to find out the stage does not support basic communication protocol.

ToDo:
- [x] add command line parameters '-e|--end-of-message' and '-E|--end-of-process'.

### CODE REVIEW

**Comment by mgolosova** [comment]
[Stage 019: параметры командной строки (-e / -E)](https://trello.com/c/hrxzPONn/43-stage-019-%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D1%8B-%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%BD%D0%BE%D0%B9-%D1%81%D1%82%D1%80%D0%BE%D0%BA%D0%B8-e-e)

**Comment by mgolosova** [comment]
Now all the changes are done.
@anastasiakaida , I\`m asking for your review as you have an experience with EOP/EOM markers handling in both shell and Python scripts, so and I believe you can notice a failure in logic whatever language it is :)

**Comment by anastasiakaida** [comment]
@mgolosova 

As I remember, markers also depend on a mode (stream/file) as it's demonstrated in 0d323e3. Couldn't catch does it follow this logic.

**Comment by mgolosova** [comment]
@anastasiakaida, right, "mode" things. Will fix it, thanks!

**Comment by mgolosova** [comment]
@anastasiakaida, fixed (along with another bu I just caught), please go on with review :)

**Pull request merged**
