### PR TITLE
Adding data from AMI

### PR DESCRIPTION
**Pull request by mgolosova**
Fields to add:
* k_factor
* cross_section
* cross_section_ref
* gen_filt_eff

ToDo:
- [x] change ES mapping;
- [x] add stage (say, 095_datasetInfoAMI):
   input from 093 (see PR #102), output -- to 019 (see PR #86);
   pyAMI with `GetPhysicsParamsForDataset` command will help;
- [x] introduce it to the `data4es` pipeline;
- [x] decide what to do with extra parameters taken from AMI (e.g. `processGroup`) -- remove, add to mapping, leave "as is"? *(`processGroup` and `mePDF` are added to mapping)* [1]
- [x] do it;
- [x] add input/output data samples;
- [x] test properly on aiatlas171;
- [x] update output example;
- [x] append 8a836c4 to where it belongs (69797cf)
- [x] append f9d740e to where it belongs (19a1d5d)
- [ ] ...
- [ ] ~batch mode for performance;~ [2]
  *However good this idea might look, it was decided to be addressed outside this PR.*
  *See #108 for details.*

---
This PR to be finished after ~#88~, ~#85~ and ~#102~ (_--@mgolosova_)

[1] However we are not sure if all the fields possible were found.
[2] AMI allows to get data for a comma-separated list of datasets and it will be faster than doing it one-by-one (see getMetadata.py by AMI):
```
datasetsToQuery = ",".join(dataset_values.keys())
res = client.execute(['GetPhysicsParamsForDataset',"--logicalDatasetName=%s"% datasetsToQuery,"--timestamp='%s'"%args.timestamp], format='dom_object')
```

### CODE REVIEW

**Comment by mgolosova** [comment]
Rebased on `stage-091-datasetsRucio` to proceed with the task.

**Comment by maria-grigorieva** [comment]
Probably we should change 'default_index' name in [esFormat](https://github.com/PanDAWMS/dkb/blob/dataflow-ami2es/Utils/Dataflow/019_esFormat/esFormat.php)?

**Comment by maria-grigorieva** [comment]
Concerning extra parameters: mePDF and processGroup - let's leave them in index. So, the corresponding changes in code (#f5a5ff8) should be accepted.

**Comment by mgolosova** [comment]
@maria-grigorieva,
will fix 'default_index' after rebasing on new #85 (where it was changed to 'prodsys_rucio'), thank you.
`mePDF` and `processGroup` -- got it :)

**Comment by mgolosova** [comment]
Original variant of the PR is storeed in `pr-84-stage-92-00` branch.

Changes after rebase:
* default index in 019 is changed to `prodsys_rucio_ami`;
* dataset filtering is aware of the fact that `data_format` value is a list;
* example input data are replaced with link to 093/output;
* stage 093 files added;
* stage 093 added to `data4es`.

ToDo list will be updated too:
- [ ] test properly on aiatlas171;
- [ ] update output example;
- [ ] append 8a836c4 to where it belongs (69797cf)
- [ ] append f9d740e to where it belongs (19a1d5d)
- [ ] ...

**Comment by mgolosova** [comment]
Previous variant of this PR is stored in `pr-84-stage-92-01` branch.

Changes after rebase:
* stage is renamed to 095;
* README is formatted to the width of 80.

**Comment by mgolosova** [comment]
Tested on `093/output` sample data.
Also need to test `data4es` start script. It will be done on Monday -- not earlier, I`m afraid.

**Comment by mgolosova** [comment]
Testing with together with #93.
Workflow is running without failure for a while now; seems like everything is Ok. Data being loaded to ES are also look alright.

Going to rebase the PR once again in order to:
* join 111efe0 and 2737152;
* join 2a13563 and 81077c1;
* join 6e2a401 and 608109c;
* remove f3526d7 (as it was moved to PR #99);
* reword a672be8 (log summary does not fit 72 symbols);

**Comment by mgolosova** [comment]
Rebasing is done; previous version of the PR is saved for reference in `pr-84-stage-95-03` branch.

Seems to me like a final version. Please review.

**Pull request merged**
