### PR TITLE
[override] Dataflow ami2es analyzer

### PR DESCRIPTION
**Pull request by maria-grigorieva**
*Update: this PR is overridden and to be closed after #84 is merged to `master`.*

---

'Standard' analyzer doesn't provide tokenization by dot. 
So 'datasetname' is splitted into tokens this way:

```
GET _analyze
{
  "analyzer": "standard",
"text":"mc15_13TeV.341997.aMcAtNloHppEG_UEEE5_CTEQ6L1_CT10ME_tWH125_gamgam_yt_minus1.evgen.EVNT.e4394_tid12651267_00"
}

{
  "tokens": [
    {
      "token": "mc15_13tev",
    },
    {
      "token": "341997",
    },
    {
      "token": "amcatnlohppeg_ueee5_cteq6l1_ct10me_twh125_gamgam_yt_minus1",
    },
    {
      "token": "evgen.evnt.e4394_tid12651267_00",
    }
  ]
}
```

Production step and data format are glued to the tags and doesn't processed separately, 
 so we can search by this fields only with regular expressions, that is not optimal in performance. 

The pattern analyzer uses a regular expression to split the text into terms. 
The regular expression should match the token separators not the tokens themselves. 
The regular expression defaults to \W+ (or all non-word characters).
[Pattern Analyzer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-pattern-analyzer.html)

```
GET _analyze
{
  "analyzer" : "pattern",
  "text":"mc16_13TeV.363128.MGPy8EG_N30NLO_Zmumu_Ht70_140_BFilter.deriv.DAOD_JETM3.e4649_s3126_r9364_r9315_p3371_tid12648221_00"
}

{
  "tokens": [
    {
      "token": "mc16_13tev",
    },
    {
      "token": "363128",
    },
    {
      "token": "mgpy8eg_n30nlo_zmumu_ht70_140_bfilter",
    },
    {
      "token": "deriv",
    },
    {
      "token": "daod_jetm3",
    },
    {
      "token": "e4649_s3126_r9364_r9315_p3371_tid12648221_00",
    }
  ]
}

```
This will allow to execute such ES queries:
```
GET prodsys_rucio_ami/task/_search
{
  "query": { 
    "match": {
     "datasetname": {
      "query": "mc16_13TeV recon aod",
      "operator": "and"
    }
    }
  }
}
```
Q1: Should we use standard pattern tokenizer [\W+] or add "_"-tokenization [\W+|_] to provide splitting physics_short fields, like "mgpy8eg_n30nlo_zmumu_ht70_140_bfilter" into tokens ['mgpy8eg', 'n30nlo', 'zmumu', 'ht70', '140', 'bfilter'].

### CODE REVIEW

**Comment by maria-grigorieva** [comment]
With custom pattern analyzer "task_dataset_analyzer" the datasetname is splitted by dot and '_'. 
Example: 
```
GET custom_analyzer/_analyze
{
  "analyzer" : "task_dataset_name",
  "text" : "mc16_13TeV:mc16_13TeV.361022.Pythia8EvtGen_A14NNPDF23LO_jetjet_JZ2W.simul.HITS.e3668_s2997_tid09756488_00"
}
```

```
{
  "tokens": [
    {
      "token": "mc16",
      "start_offset": 0,
      "end_offset": 4,
      "type": "word",
      "position": 0
    },
    {
      "token": "13tev",
      "start_offset": 5,
      "end_offset": 10,
      "type": "word",
      "position": 1
    },
    {
      "token": "mc16",
      "start_offset": 11,
      "end_offset": 15,
      "type": "word",
      "position": 2
    },
    {
      "token": "13tev",
      "start_offset": 16,
      "end_offset": 21,
      "type": "word",
      "position": 3
    },
    {
      "token": "361022",
      "start_offset": 22,
      "end_offset": 28,
      "type": "word",
      "position": 4
    },
    {
      "token": "pythia8evtgen",
      "start_offset": 29,
      "end_offset": 42,
      "type": "word",
      "position": 5
    },
    {
      "token": "a14nnpdf23lo",
      "start_offset": 43,
      "end_offset": 55,
      "type": "word",
      "position": 6
    },
    {
      "token": "jetjet",
      "start_offset": 56,
      "end_offset": 62,
      "type": "word",
      "position": 7
    },
    {
      "token": "jz2w",
      "start_offset": 63,
      "end_offset": 67,
      "type": "word",
      "position": 8
    },
    {
      "token": "simul",
      "start_offset": 68,
      "end_offset": 73,
      "type": "word",
      "position": 9
    },
    {
      "token": "hits",
      "start_offset": 74,
      "end_offset": 78,
      "type": "word",
      "position": 10
    },
    {
      "token": "e3668",
      "start_offset": 79,
      "end_offset": 84,
      "type": "word",
      "position": 11
    },
    {
      "token": "s2997",
      "start_offset": 85,
      "end_offset": 90,
      "type": "word",
      "position": 12
    },
    {
      "token": "tid09756488",
      "start_offset": 91,
      "end_offset": 102,
      "type": "word",
      "position": 13
    },
    {
      "token": "00",
      "start_offset": 103,
      "end_offset": 105,
      "type": "word",
      "position": 14
    }
  ]
}
```

**Comment by mgolosova** [comment]
As I understand, whatever analyzer we use the query string will be analyzed by the same one.
So if we choose the second variant (with `"\\W|_"`), query string like "mc16_13TeV" will be converted to `["mc16", "13tev"]` and thus will match the document.

The profit is obvious: we can avoid manual converting of task/dataset name into keywords, additional for hastags, and search for "jetjet" or something like this will still work.

The only disadvantage I could imagine was that we will be unable to search exactly by a given set of tags in given order (say, "e3668_s2997" or "gamgam_yt_minus1"). As far as I remember it was said that in some fields of task/dataset name the order is meaningful and we were asked to keep it. But as a quick search showed, we have this option of [`match_phrase`](https://www.elastic.co/guide/en/elasticsearch/guide/current/phrase-matching.html) query in ES, that does what is needed: keeps the order of terms in the query string and matches only documents where the terms are presented in the given order.

We also might fail trying to perform exact match search for "mc16_13tev" or "daod_jetm3", but for this query we have more appropriate fields, like task `campaign`, dataset `data_format` etc.

**For me the second approach looks just fine.**
Let`s discuss it at tomorrow meeting once again and decide if we can stop on it.

**Comment by mgolosova** [comment]
Marked as `[override]` as the changes from this PR are cherry-picked to the PR #84.
This PR suggested two different modifications of ES mapping and we needed only one of them, so it would make no sense to copy both of them into the main history.
But we would like to keep this PR for reference, so instead of rewriting its history the cherry-pick aproach was chosen.

This PR is to be closed after #84 is merged.

**Comment by mgolosova** [comment]
Closed, as PR #84 was succesfully merged to `master`.

**Pull request closed without merging**
