### PR TITLE
Fixed quote-processing mechanism in nestedKeys().

### PR DESCRIPTION
**Pull request by Evildoor**
- Incrementing i1 advances the cycle (it is endless with i).
- Dot is removed when split() is made, so it is added back into
quoted keys.

### CODE REVIEW

**Comment by mgolosova** [comment]
First I want to say thank you for bringing up this issue.
However I think the function still does not work as it was supposed to (sorry for the poor realization :( ).

1. It is better to remove quote marks from the keys. Now it is:
  ```
  >>> nestedKeys('a."b.c"')
  ['a', '"b.c"']
  ```
  and should be:
  ```
  >>> nestedKeys('a."b.c"')
  ['a', 'b.c']
  ```

2. We should detect unpaired quote marks as a syntax error, not as a correct pair of quotes. Now it is:
  ```
  >>> nestedKeys('a."b.c\'.d')
  ['a', '"b.c\'', 'd']
  ```
  and should be something like:
  ```
  >>> nestedKeys('a."b.c\'.d')
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "pyDKB/common/json_utils.py", line ???, in nestedKeys
      "configuration key: %s" % key)
    ValueError: Failed to decode dot-splitted configuration key: a."b.c'.d
  ```

And following this logic, another example should work this way:
```
>>> nestedKeys('a.\'b."c".d\'.e')
['a', 'b."c".d', 'e']
```

**Comment by Evildoor** [comment]
Makes sense. I can take a look, but I'll probably have to rewrite the function in such case - is that ok?

**Comment by mgolosova** [comment]
> I'll probably have to rewrite the function in such case - is that ok?

Yes, sometimes it is the only way to make things right.

**Comment by Evildoor** [comment]
Rework is done.

**Pull request merged**
