### PR TITLE
pyDKB setup script

### PR DESCRIPTION
**Pull request by mgolosova**
Add simple setup script to avoid dancing around `sys.path`.

To install the `pyDKB` library for the development, run `./pyDKB-setup.py develop`.
It will fake-install library, creating link to the directory with source
files, and there will be no need to re-install library after every
change.

To install `pyDKB` "for usage", use `./pyDKB-setup.py install`.

ToDo:
 - [x] version definition (to have same version in `setup` and `__install__`)

### CODE REVIEW

**Comment by Evildoor** [comment]
Before I delve into setuptools documentation, I'll ask: is there an equally simple option for uninstalling?

**Comment by mgolosova** [comment]
@Evildoor, I bet you have already found the answer. But no, they say you need to remove all files manually, and also undo any other stuff that installation did manually.
It usually writes during installation where it places what files, or you may use `--record` parameter to get a full list in a more straightforward way.

**Comment by Evildoor** [comment]
Tested this with virtualenv on bamboo and my machine, devel installation does not work:

    (test_pyDKB_setup) C:\Work\virtenv\test_pyDKB_setup\Work\Dataflow>python pyDKB-setup.py devel
    C:\Work\virtenv\test_pyDKB_setup\lib\site-packages\setuptools\dist.py:294: UserWarning: The version specified ('0.3-SNAPSHOT') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
    "details." % self.metadata.version
    usage: pyDKB-setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
    or: pyDKB-setup.py --help [cmd1 cmd2 ...]
    or: pyDKB-setup.py --help-commands
    or: pyDKB-setup.py cmd --help

    error: invalid command 'devel'

Full installation seems to be working.

**Comment by mgolosova** [comment]
[pyDKB-setup](https://trello.com/c/Vfdvr3TN/18-pydkb-setup)

**Comment by mgolosova** [comment]
@Evildoor, my bad: it should be `pyDKB-setup.py develop`.
Fixed the PR description accordingly.

**Comment by Evildoor** [comment]
Checked again.

1. The installation works with the `develop` command.
2. It seems that there is an easy way to uninstall the package: pip detects it and can remove it. I've not checked whether it completely undoes everything that was added and changed, but the module is correctly not found when imported after uninstalling.
3. The installation ignores `virtualenv` and installs into main system. This is not correct, I believe. This was only tested on my machine (Windows), since with such result I'm unwilling to install it on bamboo in fear of breaking something.

**Comment by mgolosova** [comment]
@evildoor,
Thanks for the clue about `pip uninstall` -- it does work, indeed.

Not sure that I your point about virtualenv usage; not very familiar with it, actually.
Tried it in Ubuntu, seems to work for me:
```
$ pwd
/home/mgolosova/work/DKB/git/Utils/Dataflow
$ virtualenv pyDKB-test
$ . pyDKB-test/bin/activate
(pyDKB-test)$ ./pyDKB-setup.py install
<...>
$ cd ..
$ pwd
/home/mgolosova/work/DKB/git/Utils
$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyDKB
(WARN) pyDKB.dataflow.cds failed (No module named invenio_client.contrib)
>>> pyDKB.__file__
'/home/mgolosova/work/svn/git.dkb-project/Utils/Dataflow/pyDKB-test/local/lib/python2.7/site-packages/pyDKB-0.3_SNAPSHOT-py2.7.egg/pyDKB/__init__.pyc'
```
>>> 

Can you please tell what commands you are runnung?
And feel free to try it on bamboo -- unless you work with root privileges, you should not be able to break anything. If you are, it\`s my fault and hence -- my problem ;)

**Comment by Evildoor** [comment]
Tested on bamboo, seems to be working properly. Ok then, I suppose we can blame it on Windows and say "we aren't developing pyDKB for Windows".

**Comment by mgolosova** [comment]
@Evildoor, yeah... thought I try to take it into account in the code (e.g. using `os.path` insead of direct manipulations with path), yet I can never be sure there\`s nothing left in the code that is *nix-specific. To make sure it works properly in Windows we should test it in Windows, which I personally never did.

Then it is merged.

**Pull request merged**
