### PR TITLE
pyDKB: merge 'master' branch

### PR DESCRIPTION
**Pull request by mgolosova**
Background:

* This PR is aimed in bringing documentation stuff to the `pyDKB` branch, to make it possible to revise and improve documentation directly in the latest version of the library.

* Documentation was requested by @Evildoor for pyDKB unit tests development.

* Unit tests were requested by @mgolosova to simplify further development of the library (as development without proper testing may sometimes lead to situations when things are broken and nobody knows about it for a long time; early fixes are much easier than late ones).

---

ToDo:
- [x] check conflicts resolution:
  - [x] Stage 091;
  - [x] `pyDKB.common.custom_readline`;
- [x] update pyDKB docs according to the code in destination branch;
- [x] check `--config` parameter in pyDKB and 009.

---
*~Can not be merged to `pyDKB` unless `pyDKB` itself is fixed (see PR #170).
After the merge `pyDKB` branch should be merged here again.~*
Everything that could be fixed was fixed.

### CODE REVIEW

**Comment by mgolosova** [comment]
As there were quite a lot of changes, both in `master` and `pyDKB`, the branch was reset to the new version of `pyDKB` before merging `master` to it.
Stage 091 conflict resolution was performed by the same scenario as in the last time, so I checked this item in the PR description.
But there was another conflict -- in `pyDKB.common.custom_readline` (docstrings).

**Comment by mgolosova** [comment]
> - [x] check conflicts resolution: `pyDKB.common.custom_readline`;

`/Utils/Dataflow/test/pyDKB/test.sh` revealed no error so I believe it means that everything is fine.

**Comment by mgolosova** [comment]
> - [x] check --config parameter in pyDKB and 009.

No conflict here, as 009 does not utilize `pyDKB.dataflow.stage` functionality yet.

**Comment by Evildoor** [comment]
I tested the data4es (with stages 025 and 069 disabled) and some separate stages, they seem to be working. I also skimmed through the changes and failed to find anything of interest.

**Comment by mgolosova** [comment]
@Evildoor,
> I tested the data4es (with stages 025 and 069 disabled) and some separate stages, they seem to be working. I also skimmed through the changes and failed to find anything of interest.
> 
Thank you!

Just a note to clarify why disabling the stages was fine for testing:
* Stage 069 shouldn’t be affected or reveal any issues (as long as 019 produces same output as before).
* Stage 025 *had* been affected in fact (as  added in `master` and was not adapted to the new version of `pyDKB` along with others), but it was fixed in last commits.

**Comment by mgolosova** [comment]
@anastasiakaida, @Evildoor, thank you both for checking this PR.

Will merge it now.

**Pull request merged**
